language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls appveyor-artifacts mock
# command to run tests
script:
  nosetests --with-coverage --cover-package=asciimatics
after_success:
  - mv .coverage .coverage.travis
  - appveyor-artifacts -m download
  - coverage combine .coverage.travis */.coverage
  - coveralls
